/*  Source: 	Insert_Supplier.sql
 *	Author:		Benjamin A Garza III
 *	Date:		April 6, 2019
 *	Class:		CMPS 3420 - Databases
 *	Purpose: 	Insert tuples to Yield.
 *
 *  Run:
 *      psql -f Insert_Supplier.sql dionysusbrewingco dionysus
 */

INSERT INTO Supplier (SupplierName, AddressID) VALUES ('eog resources', 44);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('the phoenix companies', 47);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('autozone', 44);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('united rentals', 47);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('intuit', 41);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('brown shoe company', 43);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('mylan', 48);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('united technologies corporation', 45);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('abercrombie & fitch co', 44);
INSERT INTO Supplier (SupplierName, AddressID) VALUES ('anadarko petroleum corporation', 46);


/*
insert into Supplier (SupplierName, AddressID) values ('Donnelly-Rempel', 700);
insert into Supplier (SupplierName, AddressID) values ('Gleichner-Beahan', 829);
insert into Supplier (SupplierName, AddressID) values ('Schmidt-Lowe', 567);
insert into Supplier (SupplierName, AddressID) values ('Langworth, Muller and Wehner', 721);
insert into Supplier (SupplierName, AddressID) values ('Powlowski, Graham and O''Keefe', 813);
insert into Supplier (SupplierName, AddressID) values ('Moore-Wisoky', 706);
insert into Supplier (SupplierName, AddressID) values ('Gibson-Weissnat', 746);
insert into Supplier (SupplierName, AddressID) values ('Rohan Group', 123);
insert into Supplier (SupplierName, AddressID) values ('Bartell-Romaguera', 354);
insert into Supplier (SupplierName, AddressID) values ('Kohler LLC', 417);
insert into Supplier (SupplierName, AddressID) values ('Jacobi-Bosco', 990);
insert into Supplier (SupplierName, AddressID) values ('Skiles-Ernser', 456);
insert into Supplier (SupplierName, AddressID) values ('McCullough Group', 887);
insert into Supplier (SupplierName, AddressID) values ('Halvorson, Yost and Armstrong', 922);
insert into Supplier (SupplierName, AddressID) values ('Christiansen, Greenholt and Mraz', 37);
insert into Supplier (SupplierName, AddressID) values ('Parisian and Sons', 69);
insert into Supplier (SupplierName, AddressID) values ('Collins-Little', 340);
insert into Supplier (SupplierName, AddressID) values ('Lynch, Smith and Stracke', 904);
insert into Supplier (SupplierName, AddressID) values ('Conroy-Christiansen', 125);
insert into Supplier (SupplierName, AddressID) values ('Ullrich, Prosacco and Sporer', 900);
insert into Supplier (SupplierName, AddressID) values ('Boyer-Homenick', 171);
insert into Supplier (SupplierName, AddressID) values ('Terry-Orn', 192);
insert into Supplier (SupplierName, AddressID) values ('Mitchell Group', 510);
insert into Supplier (SupplierName, AddressID) values ('Koelpin-Sanford', 487);
insert into Supplier (SupplierName, AddressID) values ('Russel-Robel', 462);
insert into Supplier (SupplierName, AddressID) values ('Cronin-Hirthe', 460);
insert into Supplier (SupplierName, AddressID) values ('Jast, Aufderhar and Kling', 349);
insert into Supplier (SupplierName, AddressID) values ('Wuckert-Paucek', 95);
insert into Supplier (SupplierName, AddressID) values ('Johnson, Lang and Kris', 205);
insert into Supplier (SupplierName, AddressID) values ('Greenfelder, Kohler and Ortiz', 178);
insert into Supplier (SupplierName, AddressID) values ('Dietrich, Gutmann and Conroy', 382);
insert into Supplier (SupplierName, AddressID) values ('Dickens Inc', 644);
insert into Supplier (SupplierName, AddressID) values ('Heathcote-Bernhard', 710);
insert into Supplier (SupplierName, AddressID) values ('Haag Group', 142);
insert into Supplier (SupplierName, AddressID) values ('Smith-Ruecker', 464);
insert into Supplier (SupplierName, AddressID) values ('Fay, Schuppe and Zemlak', 359);
insert into Supplier (SupplierName, AddressID) values ('Lebsack and Sons', 425);
insert into Supplier (SupplierName, AddressID) values ('Wehner Inc', 513);
insert into Supplier (SupplierName, AddressID) values ('Wehner, Rau and Bruen', 629);
insert into Supplier (SupplierName, AddressID) values ('Lind LLC', 334);
insert into Supplier (SupplierName, AddressID) values ('Thiel-Pollich', 170);
insert into Supplier (SupplierName, AddressID) values ('Ondricka Inc', 47);
insert into Supplier (SupplierName, AddressID) values ('O''Conner and Sons', 670);
insert into Supplier (SupplierName, AddressID) values ('Spencer-Price', 696);
insert into Supplier (SupplierName, AddressID) values ('Tromp-Orn', 34);
insert into Supplier (SupplierName, AddressID) values ('Lynch, Fahey and Von', 263);
insert into Supplier (SupplierName, AddressID) values ('Crist LLC', 904);
insert into Supplier (SupplierName, AddressID) values ('Crona and Sons', 136);
insert into Supplier (SupplierName, AddressID) values ('Stracke, Dach and Sipes', 503);
insert into Supplier (SupplierName, AddressID) values ('McClure, Harris and Lemke', 525);
insert into Supplier (SupplierName, AddressID) values ('Mertz, Lebsack and Nader', 32);
insert into Supplier (SupplierName, AddressID) values ('Mitchell Group', 363);
insert into Supplier (SupplierName, AddressID) values ('Langosh Inc', 727);
insert into Supplier (SupplierName, AddressID) values ('Haag-Abshire', 368);
insert into Supplier (SupplierName, AddressID) values ('Terry, Deckow and Eichmann', 856);
insert into Supplier (SupplierName, AddressID) values ('Cremin-Wilkinson', 319);
insert into Supplier (SupplierName, AddressID) values ('Ziemann Inc', 326);
insert into Supplier (SupplierName, AddressID) values ('Armstrong and Sons', 699);
insert into Supplier (SupplierName, AddressID) values ('Langworth, Mills and Bauch', 778);
insert into Supplier (SupplierName, AddressID) values ('Swift LLC', 985);
insert into Supplier (SupplierName, AddressID) values ('Schroeder-Heidenreich', 895);
insert into Supplier (SupplierName, AddressID) values ('Treutel Group', 357);
insert into Supplier (SupplierName, AddressID) values ('Quitzon, Bailey and Blick', 509);
insert into Supplier (SupplierName, AddressID) values ('Hudson, Pouros and Rowe', 348);
insert into Supplier (SupplierName, AddressID) values ('Conroy-Sanford', 234);
insert into Supplier (SupplierName, AddressID) values ('Graham, Collier and Green', 181);
insert into Supplier (SupplierName, AddressID) values ('Cole Group', 572);
insert into Supplier (SupplierName, AddressID) values ('Gerhold LLC', 764);
insert into Supplier (SupplierName, AddressID) values ('Batz-Hintz', 293);
insert into Supplier (SupplierName, AddressID) values ('Hackett-Waters', 338);
insert into Supplier (SupplierName, AddressID) values ('Blick Inc', 872);
insert into Supplier (SupplierName, AddressID) values ('Smith, Glover and Connelly', 536);
insert into Supplier (SupplierName, AddressID) values ('Crist and Sons', 194);
insert into Supplier (SupplierName, AddressID) values ('Kozey-Nienow', 285);
insert into Supplier (SupplierName, AddressID) values ('Huels Group', 94);
insert into Supplier (SupplierName, AddressID) values ('Hintz Inc', 786);
insert into Supplier (SupplierName, AddressID) values ('Eichmann Inc', 600);
insert into Supplier (SupplierName, AddressID) values ('Hartmann, Raynor and Doyle', 596);
insert into Supplier (SupplierName, AddressID) values ('Casper, VonRueden and Sawayn', 291);
insert into Supplier (SupplierName, AddressID) values ('Nolan-Ziemann', 617);
insert into Supplier (SupplierName, AddressID) values ('Lueilwitz and Sons', 508);
insert into Supplier (SupplierName, AddressID) values ('Pacocha Inc', 431);
insert into Supplier (SupplierName, AddressID) values ('Heidenreich-Shields', 22);
insert into Supplier (SupplierName, AddressID) values ('Schmitt, Daugherty and Kerluke', 682);
insert into Supplier (SupplierName, AddressID) values ('Jacobs Inc', 779);
insert into Supplier (SupplierName, AddressID) values ('Bogisich, Mosciski and Lebsack', 346);
insert into Supplier (SupplierName, AddressID) values ('Quitzon-Dibbert', 729);
insert into Supplier (SupplierName, AddressID) values ('Pouros-McKenzie', 154);
insert into Supplier (SupplierName, AddressID) values ('Powlowski, Murphy and Boyer', 86);
insert into Supplier (SupplierName, AddressID) values ('Swaniawski, Fadel and Harber', 772);
insert into Supplier (SupplierName, AddressID) values ('Keeling Group', 955);
insert into Supplier (SupplierName, AddressID) values ('Kulas, Quigley and Beatty', 993);
insert into Supplier (SupplierName, AddressID) values ('Yundt, Price and Hintz', 803);
insert into Supplier (SupplierName, AddressID) values ('Bernhard and Sons', 643);
insert into Supplier (SupplierName, AddressID) values ('Towne Group', 925);
insert into Supplier (SupplierName, AddressID) values ('Thompson-Abernathy', 607);
insert into Supplier (SupplierName, AddressID) values ('Heidenreich, O''Keefe and Boehm', 606);
insert into Supplier (SupplierName, AddressID) values ('Herman-Pfeffer', 506);
insert into Supplier (SupplierName, AddressID) values ('Dach-Schmidt', 240);
insert into Supplier (SupplierName, AddressID) values ('Koepp, Christiansen and Kilback', 89);
insert into Supplier (SupplierName, AddressID) values ('Kemmer, Muller and Vandervort', 650);
insert into Supplier (SupplierName, AddressID) values ('Ruecker, Flatley and Zulauf', 432);
insert into Supplier (SupplierName, AddressID) values ('Wolf-Nitzsche', 449);
insert into Supplier (SupplierName, AddressID) values ('Murazik, Kuhlman and Cronin', 557);
insert into Supplier (SupplierName, AddressID) values ('Prosacco, Bailey and Runolfsdottir', 5);
insert into Supplier (SupplierName, AddressID) values ('Sporer, Hansen and Crooks', 635);
insert into Supplier (SupplierName, AddressID) values ('Cruickshank Group', 62);
insert into Supplier (SupplierName, AddressID) values ('Wolff-Cruickshank', 754);
insert into Supplier (SupplierName, AddressID) values ('Greenholt LLC', 138);
insert into Supplier (SupplierName, AddressID) values ('Eichmann-Koelpin', 226);
insert into Supplier (SupplierName, AddressID) values ('Lueilwitz-Beahan', 1);
insert into Supplier (SupplierName, AddressID) values ('Quigley and Sons', 778);
insert into Supplier (SupplierName, AddressID) values ('Upton, Boehm and Schmitt', 643);
insert into Supplier (SupplierName, AddressID) values ('MacGyver-Gleason', 310);
insert into Supplier (SupplierName, AddressID) values ('Bruen-Kohler', 519);
insert into Supplier (SupplierName, AddressID) values ('Marvin and Sons', 530);
insert into Supplier (SupplierName, AddressID) values ('Gaylord, Collins and Osinski', 204);
insert into Supplier (SupplierName, AddressID) values ('Nolan and Sons', 186);
insert into Supplier (SupplierName, AddressID) values ('Kozey, Turner and Sipes', 735);
insert into Supplier (SupplierName, AddressID) values ('Gutmann-Stanton', 271);
insert into Supplier (SupplierName, AddressID) values ('Nolan-Cummings', 581);
insert into Supplier (SupplierName, AddressID) values ('Kassulke, Mante and Crona', 251);
insert into Supplier (SupplierName, AddressID) values ('Lakin, Vandervort and Reinger', 890);
insert into Supplier (SupplierName, AddressID) values ('Abernathy, Conroy and Effertz', 55);
insert into Supplier (SupplierName, AddressID) values ('Jacobs Inc', 74);
insert into Supplier (SupplierName, AddressID) values ('Stark-Haag', 833);
insert into Supplier (SupplierName, AddressID) values ('Johnson LLC', 649);
insert into Supplier (SupplierName, AddressID) values ('Smith, Fisher and Wilkinson', 960);
insert into Supplier (SupplierName, AddressID) values ('Marquardt, Armstrong and Zieme', 948);
insert into Supplier (SupplierName, AddressID) values ('Barton and Sons', 135);
insert into Supplier (SupplierName, AddressID) values ('Aufderhar Inc', 595);
insert into Supplier (SupplierName, AddressID) values ('Bradtke LLC', 671);
insert into Supplier (SupplierName, AddressID) values ('Wolf, Cartwright and Hickle', 264);
insert into Supplier (SupplierName, AddressID) values ('Nikolaus, Strosin and Considine', 946);
insert into Supplier (SupplierName, AddressID) values ('Ullrich, Emmerich and O''Reilly', 901);
insert into Supplier (SupplierName, AddressID) values ('Kessler, Armstrong and Marvin', 91);
insert into Supplier (SupplierName, AddressID) values ('Mueller LLC', 620);
insert into Supplier (SupplierName, AddressID) values ('Franecki, Stracke and Gleichner', 273);
insert into Supplier (SupplierName, AddressID) values ('Flatley, Pacocha and Raynor', 346);
insert into Supplier (SupplierName, AddressID) values ('Littel, Herman and Kuhlman', 455);
insert into Supplier (SupplierName, AddressID) values ('Wintheiser-Hamill', 323);
insert into Supplier (SupplierName, AddressID) values ('Dare and Sons', 671);
insert into Supplier (SupplierName, AddressID) values ('Kozey, Toy and Ruecker', 142);
insert into Supplier (SupplierName, AddressID) values ('Spencer-Kertzmann', 134);
insert into Supplier (SupplierName, AddressID) values ('Wolf and Sons', 849);
insert into Supplier (SupplierName, AddressID) values ('Klein, Harris and Schaefer', 826);
insert into Supplier (SupplierName, AddressID) values ('Cummerata, Koelpin and Quitzon', 573);
insert into Supplier (SupplierName, AddressID) values ('Bauch, Jacobs and Greenfelder', 452);
insert into Supplier (SupplierName, AddressID) values ('Ullrich, Ebert and Powlowski', 2);
insert into Supplier (SupplierName, AddressID) values ('Kozey-Terry', 396);
insert into Supplier (SupplierName, AddressID) values ('Hodkiewicz, Dach and Schmeler', 327);
insert into Supplier (SupplierName, AddressID) values ('Grimes-Turcotte', 797);
insert into Supplier (SupplierName, AddressID) values ('Aufderhar, Hilll and West', 762);
insert into Supplier (SupplierName, AddressID) values ('Robel and Sons', 994);
insert into Supplier (SupplierName, AddressID) values ('Boehm-Kihn', 779);
insert into Supplier (SupplierName, AddressID) values ('Rempel, Howe and Watsica', 729);
insert into Supplier (SupplierName, AddressID) values ('Smitham, Durgan and Kuhn', 873);
insert into Supplier (SupplierName, AddressID) values ('Baumbach-Smitham', 404);
insert into Supplier (SupplierName, AddressID) values ('Hauck-Pollich', 107);
insert into Supplier (SupplierName, AddressID) values ('Mertz Group', 927);
insert into Supplier (SupplierName, AddressID) values ('Carroll Inc', 225);
insert into Supplier (SupplierName, AddressID) values ('Hettinger, Hermiston and Doyle', 37);
insert into Supplier (SupplierName, AddressID) values ('Bergstrom Inc', 851);
insert into Supplier (SupplierName, AddressID) values ('Morissette LLC', 490);
insert into Supplier (SupplierName, AddressID) values ('Nikolaus Inc', 948);
insert into Supplier (SupplierName, AddressID) values ('Kunze, Runolfsdottir and Heller', 67);
insert into Supplier (SupplierName, AddressID) values ('Hagenes, Breitenberg and Vandervort', 717);
insert into Supplier (SupplierName, AddressID) values ('Nitzsche and Sons', 698);
insert into Supplier (SupplierName, AddressID) values ('Brekke LLC', 189);
insert into Supplier (SupplierName, AddressID) values ('Torp, Runolfsson and Runolfsdottir', 927);
insert into Supplier (SupplierName, AddressID) values ('Murazik and Sons', 901);
insert into Supplier (SupplierName, AddressID) values ('Hane-West', 708);
insert into Supplier (SupplierName, AddressID) values ('Reinger-Gleason', 580);
insert into Supplier (SupplierName, AddressID) values ('Herzog-Veum', 659);
insert into Supplier (SupplierName, AddressID) values ('Kulas and Sons', 871);
insert into Supplier (SupplierName, AddressID) values ('Yundt, Hudson and Trantow', 778);
insert into Supplier (SupplierName, AddressID) values ('Reilly LLC', 637);
insert into Supplier (SupplierName, AddressID) values ('Wintheiser, Gulgowski and Brown', 573);
insert into Supplier (SupplierName, AddressID) values ('Bergstrom, Dibbert and Larkin', 407);
insert into Supplier (SupplierName, AddressID) values ('Okuneva, Terry and Kub', 580);
insert into Supplier (SupplierName, AddressID) values ('Dare, Macejkovic and Huels', 208);
insert into Supplier (SupplierName, AddressID) values ('Krajcik-West', 170);
insert into Supplier (SupplierName, AddressID) values ('Kohler Inc', 726);
insert into Supplier (SupplierName, AddressID) values ('Adams, Bode and Greenfelder', 927);
insert into Supplier (SupplierName, AddressID) values ('Kris-Yost', 194);
insert into Supplier (SupplierName, AddressID) values ('Bailey and Sons', 899);
insert into Supplier (SupplierName, AddressID) values ('Raynor, Champlin and Gislason', 602);
insert into Supplier (SupplierName, AddressID) values ('Dooley, Pagac and Goodwin', 274);
insert into Supplier (SupplierName, AddressID) values ('King LLC', 939);
insert into Supplier (SupplierName, AddressID) values ('Dooley, Schowalter and Yost', 898);
insert into Supplier (SupplierName, AddressID) values ('Feest LLC', 966);
insert into Supplier (SupplierName, AddressID) values ('Bruen, Conroy and Davis', 840);
insert into Supplier (SupplierName, AddressID) values ('Wolff, King and Schuppe', 796);
insert into Supplier (SupplierName, AddressID) values ('Feil LLC', 745);
insert into Supplier (SupplierName, AddressID) values ('Abbott, Sawayn and Abshire', 469);
insert into Supplier (SupplierName, AddressID) values ('Bernier Group', 354);
insert into Supplier (SupplierName, AddressID) values ('Dibbert, Marvin and Conroy', 813);
insert into Supplier (SupplierName, AddressID) values ('Towne-Erdman', 201);
insert into Supplier (SupplierName, AddressID) values ('Harvey-Buckridge', 640);
insert into Supplier (SupplierName, AddressID) values ('Marvin, Heathcote and Goldner', 818);
insert into Supplier (SupplierName, AddressID) values ('Conroy Group', 91);
insert into Supplier (SupplierName, AddressID) values ('Schuster Inc', 784);
insert into Supplier (SupplierName, AddressID) values ('Lang LLC', 21);
insert into Supplier (SupplierName, AddressID) values ('Heaney, Lindgren and Bernier', 711);
insert into Supplier (SupplierName, AddressID) values ('Dietrich-Volkman', 204);
insert into Supplier (SupplierName, AddressID) values ('Stoltenberg, Bartell and Conn', 25);
insert into Supplier (SupplierName, AddressID) values ('Harvey-Friesen', 914);
insert into Supplier (SupplierName, AddressID) values ('Lockman, Heathcote and Lemke', 396);
insert into Supplier (SupplierName, AddressID) values ('Funk, Schuster and Hartmann', 927);
insert into Supplier (SupplierName, AddressID) values ('Altenwerth Group', 101);
insert into Supplier (SupplierName, AddressID) values ('Bahringer-Rosenbaum', 711);
insert into Supplier (SupplierName, AddressID) values ('Rice-Prohaska', 47);
insert into Supplier (SupplierName, AddressID) values ('Blanda-Abernathy', 654);
insert into Supplier (SupplierName, AddressID) values ('Cremin-Nader', 63);
insert into Supplier (SupplierName, AddressID) values ('Lindgren, Wunsch and Nolan', 676);
insert into Supplier (SupplierName, AddressID) values ('Grady, Nicolas and Zulauf', 171);
insert into Supplier (SupplierName, AddressID) values ('Fadel and Sons', 275);
insert into Supplier (SupplierName, AddressID) values ('Stoltenberg, Quitzon and Kessler', 362);
insert into Supplier (SupplierName, AddressID) values ('Mitchell-Kulas', 311);
insert into Supplier (SupplierName, AddressID) values ('Lesch-Shanahan', 543);
insert into Supplier (SupplierName, AddressID) values ('Rowe, Trantow and Williamson', 867);
insert into Supplier (SupplierName, AddressID) values ('Simonis Group', 967);
insert into Supplier (SupplierName, AddressID) values ('Koch, Gleason and Schmitt', 569);
insert into Supplier (SupplierName, AddressID) values ('Rosenbaum-Balistreri', 788);
insert into Supplier (SupplierName, AddressID) values ('Hills-Treutel', 805);
insert into Supplier (SupplierName, AddressID) values ('Cole Inc', 506);
insert into Supplier (SupplierName, AddressID) values ('Weber LLC', 453);
insert into Supplier (SupplierName, AddressID) values ('Bernhard, Haley and Gerlach', 187);
insert into Supplier (SupplierName, AddressID) values ('Bogisich-Monahan', 216);
insert into Supplier (SupplierName, AddressID) values ('Bode-Fay', 193);
insert into Supplier (SupplierName, AddressID) values ('Crooks LLC', 306);
insert into Supplier (SupplierName, AddressID) values ('Spinka, Robel and Runolfsdottir', 607);
insert into Supplier (SupplierName, AddressID) values ('Blick-Flatley', 471);
insert into Supplier (SupplierName, AddressID) values ('Johnson-Bernier', 437);
insert into Supplier (SupplierName, AddressID) values ('Leannon and Sons', 896);
insert into Supplier (SupplierName, AddressID) values ('Lesch Group', 864);
insert into Supplier (SupplierName, AddressID) values ('Glover and Sons', 255);
insert into Supplier (SupplierName, AddressID) values ('Lang, Quigley and Lowe', 706);
insert into Supplier (SupplierName, AddressID) values ('Dibbert, Cronin and Mraz', 266);
insert into Supplier (SupplierName, AddressID) values ('Kozey Inc', 596);
insert into Supplier (SupplierName, AddressID) values ('Stehr, Shanahan and Shanahan', 916);
insert into Supplier (SupplierName, AddressID) values ('Schiller and Sons', 381);
insert into Supplier (SupplierName, AddressID) values ('Davis, Romaguera and Bradtke', 191);
insert into Supplier (SupplierName, AddressID) values ('Bartell Group', 989);
insert into Supplier (SupplierName, AddressID) values ('Stark, Schumm and Wiegand', 717);
insert into Supplier (SupplierName, AddressID) values ('Schinner, Davis and Klein', 970);
insert into Supplier (SupplierName, AddressID) values ('Jaskolski-Braun', 179);
insert into Supplier (SupplierName, AddressID) values ('Towne, Beahan and O''Kon', 688);
insert into Supplier (SupplierName, AddressID) values ('Jerde Inc', 29);
insert into Supplier (SupplierName, AddressID) values ('Witting-Larkin', 195);
insert into Supplier (SupplierName, AddressID) values ('Reynolds, Littel and Lindgren', 375);
insert into Supplier (SupplierName, AddressID) values ('Stokes-Prosacco', 671);
insert into Supplier (SupplierName, AddressID) values ('Wolf Inc', 383);
insert into Supplier (SupplierName, AddressID) values ('Schmitt Inc', 732);
insert into Supplier (SupplierName, AddressID) values ('Labadie, Sporer and Watsica', 235);
insert into Supplier (SupplierName, AddressID) values ('Littel-Parker', 120);
insert into Supplier (SupplierName, AddressID) values ('Murazik, Rolfson and Towne', 633);
insert into Supplier (SupplierName, AddressID) values ('Bode, Lowe and Powlowski', 298);
insert into Supplier (SupplierName, AddressID) values ('Ziemann Inc', 493);
insert into Supplier (SupplierName, AddressID) values ('Torp-Eichmann', 297);
insert into Supplier (SupplierName, AddressID) values ('Langosh Inc', 43);
insert into Supplier (SupplierName, AddressID) values ('Strosin LLC', 985);
insert into Supplier (SupplierName, AddressID) values ('Hoppe, Kilback and Koelpin', 633);
insert into Supplier (SupplierName, AddressID) values ('Durgan, Erdman and Kuvalis', 241);
insert into Supplier (SupplierName, AddressID) values ('Lakin-Purdy', 671);
insert into Supplier (SupplierName, AddressID) values ('Hoeger, Harvey and Kshlerin', 599);
insert into Supplier (SupplierName, AddressID) values ('McLaughlin-Leffler', 20);
insert into Supplier (SupplierName, AddressID) values ('Lueilwitz, Durgan and Gibson', 691);
insert into Supplier (SupplierName, AddressID) values ('Pagac-Stehr', 343);
insert into Supplier (SupplierName, AddressID) values ('Conroy, Schuppe and Tromp', 786);
insert into Supplier (SupplierName, AddressID) values ('Pouros-Grady', 544);
insert into Supplier (SupplierName, AddressID) values ('Feest-Barrows', 430);
insert into Supplier (SupplierName, AddressID) values ('Denesik-Quigley', 261);
insert into Supplier (SupplierName, AddressID) values ('Dare Inc', 251);
insert into Supplier (SupplierName, AddressID) values ('Pfeffer Inc', 682);
insert into Supplier (SupplierName, AddressID) values ('Funk Group', 73);
insert into Supplier (SupplierName, AddressID) values ('Weimann, Swift and Grady', 59);
insert into Supplier (SupplierName, AddressID) values ('Smitham-Rippin', 817);
insert into Supplier (SupplierName, AddressID) values ('Jenkins, Morar and Hessel', 558);
insert into Supplier (SupplierName, AddressID) values ('Larkin-Larkin', 491);
insert into Supplier (SupplierName, AddressID) values ('Bashirian, Prosacco and Bartell', 417);
insert into Supplier (SupplierName, AddressID) values ('Runolfsson, Emard and Toy', 662);
insert into Supplier (SupplierName, AddressID) values ('Trantow-Veum', 913);
insert into Supplier (SupplierName, AddressID) values ('Aufderhar-Bailey', 437);
insert into Supplier (SupplierName, AddressID) values ('Bradtke and Sons', 290);
insert into Supplier (SupplierName, AddressID) values ('Friesen, Baumbach and Fay', 201);
insert into Supplier (SupplierName, AddressID) values ('Bartoletti-Kuhic', 127);
insert into Supplier (SupplierName, AddressID) values ('Mueller-O''Hara', 406);
insert into Supplier (SupplierName, AddressID) values ('Collier LLC', 711);
insert into Supplier (SupplierName, AddressID) values ('Schumm-White', 778);
insert into Supplier (SupplierName, AddressID) values ('Trantow-White', 685);
insert into Supplier (SupplierName, AddressID) values ('Ruecker, Lockman and Wiegand', 976);
insert into Supplier (SupplierName, AddressID) values ('Yost-O''Reilly', 334);
insert into Supplier (SupplierName, AddressID) values ('Bailey Group', 414);
insert into Supplier (SupplierName, AddressID) values ('Jacobi Inc', 473);
insert into Supplier (SupplierName, AddressID) values ('Cronin-Ankunding', 133);
insert into Supplier (SupplierName, AddressID) values ('Spencer-Pouros', 453);
insert into Supplier (SupplierName, AddressID) values ('Gibson-Haley', 91);
insert into Supplier (SupplierName, AddressID) values ('Ullrich, Mosciski and Friesen', 834);
insert into Supplier (SupplierName, AddressID) values ('Schinner, Lemke and Steuber', 177);
insert into Supplier (SupplierName, AddressID) values ('Hermann, Ullrich and Nicolas', 979);
insert into Supplier (SupplierName, AddressID) values ('Rodriguez-Borer', 358);
insert into Supplier (SupplierName, AddressID) values ('Swift-Schimmel', 769);
insert into Supplier (SupplierName, AddressID) values ('Gleason, Schultz and Kilback', 969);
insert into Supplier (SupplierName, AddressID) values ('Weissnat and Sons', 376);
insert into Supplier (SupplierName, AddressID) values ('Feeney, Howell and Satterfield', 289);
insert into Supplier (SupplierName, AddressID) values ('Ledner, Reynolds and Walker', 901);
insert into Supplier (SupplierName, AddressID) values ('Cummings and Sons', 50);
insert into Supplier (SupplierName, AddressID) values ('Wuckert, Mertz and Gerhold', 742);
insert into Supplier (SupplierName, AddressID) values ('Corkery-Kohler', 285);
insert into Supplier (SupplierName, AddressID) values ('Legros-Swift', 123);
insert into Supplier (SupplierName, AddressID) values ('McDermott LLC', 638);
insert into Supplier (SupplierName, AddressID) values ('Ferry-Morar', 377);
insert into Supplier (SupplierName, AddressID) values ('Kassulke Group', 449);
insert into Supplier (SupplierName, AddressID) values ('Upton Inc', 724);
insert into Supplier (SupplierName, AddressID) values ('Considine-Ritchie', 995);
insert into Supplier (SupplierName, AddressID) values ('Beier LLC', 941);
insert into Supplier (SupplierName, AddressID) values ('Fahey-Thompson', 331);
insert into Supplier (SupplierName, AddressID) values ('Mayert-Prohaska', 68);
insert into Supplier (SupplierName, AddressID) values ('Casper-Harvey', 380);
insert into Supplier (SupplierName, AddressID) values ('Ortiz, Cummerata and Stokes', 358);
insert into Supplier (SupplierName, AddressID) values ('Lindgren-Heidenreich', 862);
insert into Supplier (SupplierName, AddressID) values ('Emard Inc', 776);
insert into Supplier (SupplierName, AddressID) values ('Rice Inc', 615);
insert into Supplier (SupplierName, AddressID) values ('Luettgen-Littel', 883);
insert into Supplier (SupplierName, AddressID) values ('Yundt Inc', 5);
insert into Supplier (SupplierName, AddressID) values ('Bergstrom, Bernier and Haag', 648);
insert into Supplier (SupplierName, AddressID) values ('Schmitt and Sons', 254);
insert into Supplier (SupplierName, AddressID) values ('Lebsack-Watsica', 565);
insert into Supplier (SupplierName, AddressID) values ('Kihn, Klocko and Connelly', 653);
insert into Supplier (SupplierName, AddressID) values ('Kris, Kohler and Zulauf', 120);
insert into Supplier (SupplierName, AddressID) values ('Purdy, Daniel and Windler', 388);
insert into Supplier (SupplierName, AddressID) values ('Williamson-Lockman', 863);
insert into Supplier (SupplierName, AddressID) values ('Dicki-Schiller', 192);
insert into Supplier (SupplierName, AddressID) values ('Cartwright-Kertzmann', 632);
insert into Supplier (SupplierName, AddressID) values ('Nikolaus, Heaney and Fisher', 380);
insert into Supplier (SupplierName, AddressID) values ('Moore-Goldner', 498);
insert into Supplier (SupplierName, AddressID) values ('Balistreri-Howe', 491);
insert into Supplier (SupplierName, AddressID) values ('Pacocha, Lesch and Aufderhar', 596);
insert into Supplier (SupplierName, AddressID) values ('Pollich and Sons', 808);
insert into Supplier (SupplierName, AddressID) values ('Kshlerin-Rippin', 616);
insert into Supplier (SupplierName, AddressID) values ('Bergstrom-Stehr', 917);
insert into Supplier (SupplierName, AddressID) values ('Gleichner LLC', 956);
insert into Supplier (SupplierName, AddressID) values ('Lynch Group', 966);
insert into Supplier (SupplierName, AddressID) values ('Dietrich, Schaefer and Cole', 356);
insert into Supplier (SupplierName, AddressID) values ('D''Amore-Ritchie', 97);
insert into Supplier (SupplierName, AddressID) values ('Gutkowski-Marvin', 347);
insert into Supplier (SupplierName, AddressID) values ('Crona, Moen and Walter', 603);
insert into Supplier (SupplierName, AddressID) values ('Reichel Inc', 304);
insert into Supplier (SupplierName, AddressID) values ('Roob, Nienow and Feest', 450);
insert into Supplier (SupplierName, AddressID) values ('Schinner, Marvin and Dach', 833);
insert into Supplier (SupplierName, AddressID) values ('Schmeler and Sons', 222);
insert into Supplier (SupplierName, AddressID) values ('Murray Inc', 524);
insert into Supplier (SupplierName, AddressID) values ('Kohler-Haag', 138);
insert into Supplier (SupplierName, AddressID) values ('Batz and Sons', 251);
insert into Supplier (SupplierName, AddressID) values ('Hagenes, Kozey and Douglas', 898);
insert into Supplier (SupplierName, AddressID) values ('Conroy Inc', 554);
insert into Supplier (SupplierName, AddressID) values ('Maggio-Wolff', 576);
insert into Supplier (SupplierName, AddressID) values ('Bode Group', 148);
insert into Supplier (SupplierName, AddressID) values ('Kuhn, Weissnat and Bogan', 888);
insert into Supplier (SupplierName, AddressID) values ('Rolfson, Considine and Christiansen', 227);
insert into Supplier (SupplierName, AddressID) values ('Effertz, Predovic and Rippin', 104);
insert into Supplier (SupplierName, AddressID) values ('Abshire, Turcotte and Oberbrunner', 809);
insert into Supplier (SupplierName, AddressID) values ('Turner-Grant', 387);
insert into Supplier (SupplierName, AddressID) values ('Abernathy, Langosh and Hartmann', 533);
insert into Supplier (SupplierName, AddressID) values ('D''Amore-Lang', 536);
insert into Supplier (SupplierName, AddressID) values ('Murazik, Brakus and Wehner', 894);
insert into Supplier (SupplierName, AddressID) values ('Langosh, Graham and Robel', 56);
insert into Supplier (SupplierName, AddressID) values ('Adams-Koelpin', 424);
insert into Supplier (SupplierName, AddressID) values ('Zemlak, Trantow and Hermann', 84);
insert into Supplier (SupplierName, AddressID) values ('Parker and Sons', 617);
insert into Supplier (SupplierName, AddressID) values ('Kassulke-Brakus', 564);
insert into Supplier (SupplierName, AddressID) values ('Greenholt, Hills and Weissnat', 849);
insert into Supplier (SupplierName, AddressID) values ('Jerde-Doyle', 418);
insert into Supplier (SupplierName, AddressID) values ('Lang-Schmidt', 114);
insert into Supplier (SupplierName, AddressID) values ('Wilkinson, Wintheiser and Murazik', 545);
insert into Supplier (SupplierName, AddressID) values ('Lang, Cremin and Krajcik', 592);
insert into Supplier (SupplierName, AddressID) values ('Tromp LLC', 150);
insert into Supplier (SupplierName, AddressID) values ('Parker and Sons', 742);
insert into Supplier (SupplierName, AddressID) values ('Gislason LLC', 56);
insert into Supplier (SupplierName, AddressID) values ('Reynolds and Sons', 887);
insert into Supplier (SupplierName, AddressID) values ('MacGyver and Sons', 680);
insert into Supplier (SupplierName, AddressID) values ('Schmeler, Jacobi and Bashirian', 370);
insert into Supplier (SupplierName, AddressID) values ('Kirlin LLC', 324);
insert into Supplier (SupplierName, AddressID) values ('Schuster, Roob and Blanda', 527);
insert into Supplier (SupplierName, AddressID) values ('Rau, Brekke and Hand', 916);
insert into Supplier (SupplierName, AddressID) values ('Volkman Group', 229);
insert into Supplier (SupplierName, AddressID) values ('Ruecker, Hackett and Reinger', 698);
insert into Supplier (SupplierName, AddressID) values ('Mann-Hegmann', 177);
insert into Supplier (SupplierName, AddressID) values ('Stark, Stark and Conn', 764);
insert into Supplier (SupplierName, AddressID) values ('Casper, Weissnat and Harvey', 705);
insert into Supplier (SupplierName, AddressID) values ('Runolfsdottir Inc', 411);
insert into Supplier (SupplierName, AddressID) values ('MacGyver, Bernhard and Ryan', 875);
insert into Supplier (SupplierName, AddressID) values ('Bednar Group', 305);
insert into Supplier (SupplierName, AddressID) values ('Deckow Group', 444);
insert into Supplier (SupplierName, AddressID) values ('Runolfsson Inc', 722);
insert into Supplier (SupplierName, AddressID) values ('Hoeger Group', 125);
insert into Supplier (SupplierName, AddressID) values ('Doyle, Koelpin and Hirthe', 46);
insert into Supplier (SupplierName, AddressID) values ('Haley-Gusikowski', 438);
insert into Supplier (SupplierName, AddressID) values ('Donnelly-Altenwerth', 296);
insert into Supplier (SupplierName, AddressID) values ('Bode and Sons', 427);
insert into Supplier (SupplierName, AddressID) values ('Jerde, Tromp and Schultz', 491);
insert into Supplier (SupplierName, AddressID) values ('Monahan-Hessel', 949);
insert into Supplier (SupplierName, AddressID) values ('Lemke, Reichert and Fay', 888);
insert into Supplier (SupplierName, AddressID) values ('Tillman and Sons', 988);
insert into Supplier (SupplierName, AddressID) values ('Leuschke LLC', 488);
insert into Supplier (SupplierName, AddressID) values ('Weber Inc', 195);
insert into Supplier (SupplierName, AddressID) values ('Cruickshank Group', 264);
insert into Supplier (SupplierName, AddressID) values ('Kuvalis and Sons', 280);
insert into Supplier (SupplierName, AddressID) values ('Fritsch-Buckridge', 232);
insert into Supplier (SupplierName, AddressID) values ('Nader, Ryan and Abshire', 975);
insert into Supplier (SupplierName, AddressID) values ('Rath, Hartmann and Orn', 623);
insert into Supplier (SupplierName, AddressID) values ('Larkin-Russel', 784);
insert into Supplier (SupplierName, AddressID) values ('Reichel Group', 385);
insert into Supplier (SupplierName, AddressID) values ('Abernathy-Tremblay', 338);
insert into Supplier (SupplierName, AddressID) values ('Johnston-Hahn', 546);
insert into Supplier (SupplierName, AddressID) values ('Corkery, Lueilwitz and Tremblay', 403);
insert into Supplier (SupplierName, AddressID) values ('Rogahn, Crooks and Rau', 674);
insert into Supplier (SupplierName, AddressID) values ('Thiel-Weber', 23);
insert into Supplier (SupplierName, AddressID) values ('Labadie, Kunze and Wiza', 895);
insert into Supplier (SupplierName, AddressID) values ('Beatty, Schneider and Gorczany', 965);
insert into Supplier (SupplierName, AddressID) values ('Schamberger, Kemmer and Okuneva', 527);
insert into Supplier (SupplierName, AddressID) values ('Koch-Berge', 341);
insert into Supplier (SupplierName, AddressID) values ('Klein-Keebler', 187);
insert into Supplier (SupplierName, AddressID) values ('Wilderman-Labadie', 810);
insert into Supplier (SupplierName, AddressID) values ('Trantow and Sons', 997);
insert into Supplier (SupplierName, AddressID) values ('Gutkowski-Stanton', 796);
insert into Supplier (SupplierName, AddressID) values ('Pacocha-Nitzsche', 998);
insert into Supplier (SupplierName, AddressID) values ('Robel, Lind and Kirlin', 406);
insert into Supplier (SupplierName, AddressID) values ('Padberg, Windler and Labadie', 681);
insert into Supplier (SupplierName, AddressID) values ('Wilkinson, Koelpin and Kreiger', 966);
insert into Supplier (SupplierName, AddressID) values ('Watsica-Anderson', 588);
insert into Supplier (SupplierName, AddressID) values ('Haley-Anderson', 985);
insert into Supplier (SupplierName, AddressID) values ('Zboncak Group', 863);
insert into Supplier (SupplierName, AddressID) values ('Runolfsson Inc', 833);
insert into Supplier (SupplierName, AddressID) values ('Bruen LLC', 513);
insert into Supplier (SupplierName, AddressID) values ('Thompson-Kihn', 485);
insert into Supplier (SupplierName, AddressID) values ('Treutel and Sons', 53);
insert into Supplier (SupplierName, AddressID) values ('Runolfsdottir, King and Toy', 177);
insert into Supplier (SupplierName, AddressID) values ('Reinger, Rutherford and Wolf', 963);
insert into Supplier (SupplierName, AddressID) values ('King and Sons', 108);
insert into Supplier (SupplierName, AddressID) values ('Hyatt Inc', 687);
insert into Supplier (SupplierName, AddressID) values ('Morar-Hoeger', 694);
insert into Supplier (SupplierName, AddressID) values ('Gutkowski, Roberts and Mills', 660);
insert into Supplier (SupplierName, AddressID) values ('Borer Inc', 879);
insert into Supplier (SupplierName, AddressID) values ('Nolan, Friesen and Champlin', 454);
insert into Supplier (SupplierName, AddressID) values ('Keebler-Murray', 185);
insert into Supplier (SupplierName, AddressID) values ('Ebert LLC', 313);
insert into Supplier (SupplierName, AddressID) values ('Luettgen, Kuphal and Fahey', 24);
insert into Supplier (SupplierName, AddressID) values ('Conroy Inc', 848);
insert into Supplier (SupplierName, AddressID) values ('Predovic Inc', 440);
insert into Supplier (SupplierName, AddressID) values ('Barton-Hammes', 670);
insert into Supplier (SupplierName, AddressID) values ('Schuppe, Cremin and Schuppe', 87);
insert into Supplier (SupplierName, AddressID) values ('Mann-Shanahan', 763);
insert into Supplier (SupplierName, AddressID) values ('Mills-Lebsack', 610);
insert into Supplier (SupplierName, AddressID) values ('Douglas-Stracke', 199);
insert into Supplier (SupplierName, AddressID) values ('Schimmel-Okuneva', 617);
insert into Supplier (SupplierName, AddressID) values ('Ruecker-Muller', 794);
insert into Supplier (SupplierName, AddressID) values ('Ullrich-Klocko', 350);
insert into Supplier (SupplierName, AddressID) values ('Mueller, Monahan and Kirlin', 613);
insert into Supplier (SupplierName, AddressID) values ('Blick and Sons', 78);
insert into Supplier (SupplierName, AddressID) values ('Rutherford-Hamill', 807);
insert into Supplier (SupplierName, AddressID) values ('Bailey, Bode and Morar', 466);
insert into Supplier (SupplierName, AddressID) values ('Schulist-Kub', 373);
insert into Supplier (SupplierName, AddressID) values ('Gleason, Goyette and Stroman', 403);
insert into Supplier (SupplierName, AddressID) values ('Bergstrom, Schuppe and Reinger', 533);
insert into Supplier (SupplierName, AddressID) values ('Welch Group', 92);
insert into Supplier (SupplierName, AddressID) values ('Dicki, Hayes and Wintheiser', 933);
insert into Supplier (SupplierName, AddressID) values ('Mraz-Jaskolski', 790);
insert into Supplier (SupplierName, AddressID) values ('Jerde-Howell', 452);
insert into Supplier (SupplierName, AddressID) values ('Keeling-Balistreri', 274);
insert into Supplier (SupplierName, AddressID) values ('Jacobson-Block', 487);
insert into Supplier (SupplierName, AddressID) values ('Collier-Mertz', 459);
insert into Supplier (SupplierName, AddressID) values ('Kozey-Gusikowski', 463);
insert into Supplier (SupplierName, AddressID) values ('Reilly, Mills and Legros', 527);
insert into Supplier (SupplierName, AddressID) values ('Lakin-Gottlieb', 846);
insert into Supplier (SupplierName, AddressID) values ('Rempel LLC', 635);
insert into Supplier (SupplierName, AddressID) values ('Keeling-Anderson', 275);
insert into Supplier (SupplierName, AddressID) values ('Botsford, Schmeler and Marks', 781);
insert into Supplier (SupplierName, AddressID) values ('Corkery Group', 462);
insert into Supplier (SupplierName, AddressID) values ('Schinner Group', 998);
insert into Supplier (SupplierName, AddressID) values ('Rau-Zboncak', 449);
insert into Supplier (SupplierName, AddressID) values ('Feil, Wuckert and Armstrong', 100);
insert into Supplier (SupplierName, AddressID) values ('Schmitt, Larson and Jacobi', 320);
insert into Supplier (SupplierName, AddressID) values ('Koepp, Bednar and Runolfsdottir', 700);
insert into Supplier (SupplierName, AddressID) values ('Kemmer LLC', 770);
insert into Supplier (SupplierName, AddressID) values ('Luettgen Group', 710);
insert into Supplier (SupplierName, AddressID) values ('Streich-Murphy', 433);
insert into Supplier (SupplierName, AddressID) values ('Auer, Thiel and Gerlach', 147);
insert into Supplier (SupplierName, AddressID) values ('Murphy-Jones', 136);
insert into Supplier (SupplierName, AddressID) values ('Ritchie, Luettgen and Hane', 882);
insert into Supplier (SupplierName, AddressID) values ('Bartell Inc', 494);
insert into Supplier (SupplierName, AddressID) values ('Howe, Kuhlman and Ferry', 735);
insert into Supplier (SupplierName, AddressID) values ('Reynolds-Durgan', 289);
insert into Supplier (SupplierName, AddressID) values ('Eichmann, Carroll and Terry', 945);
insert into Supplier (SupplierName, AddressID) values ('Yost LLC', 913);
insert into Supplier (SupplierName, AddressID) values ('Moen Group', 954);
insert into Supplier (SupplierName, AddressID) values ('Schamberger LLC', 979);
insert into Supplier (SupplierName, AddressID) values ('Reichel, Jerde and Lowe', 378);
insert into Supplier (SupplierName, AddressID) values ('Hamill-Grimes', 318);
insert into Supplier (SupplierName, AddressID) values ('Donnelly-O''Keefe', 108);
insert into Supplier (SupplierName, AddressID) values ('Heaney-Larkin', 596);
insert into Supplier (SupplierName, AddressID) values ('Lockman, Walsh and Williamson', 908);
insert into Supplier (SupplierName, AddressID) values ('Schmeler Inc', 998);
insert into Supplier (SupplierName, AddressID) values ('Jones and Sons', 504);
insert into Supplier (SupplierName, AddressID) values ('Baumbach Inc', 453);
insert into Supplier (SupplierName, AddressID) values ('Rosenbaum-Botsford', 537);
insert into Supplier (SupplierName, AddressID) values ('Zieme, Bechtelar and Abernathy', 282);
insert into Supplier (SupplierName, AddressID) values ('Mills and Sons', 515);
insert into Supplier (SupplierName, AddressID) values ('Glover Group', 15);
insert into Supplier (SupplierName, AddressID) values ('Hagenes and Sons', 806);
insert into Supplier (SupplierName, AddressID) values ('Hayes LLC', 452);
insert into Supplier (SupplierName, AddressID) values ('Lindgren-Roob', 356);
insert into Supplier (SupplierName, AddressID) values ('Botsford-Braun', 174);
insert into Supplier (SupplierName, AddressID) values ('Lockman, Schinner and Runolfsson', 420);
insert into Supplier (SupplierName, AddressID) values ('Murphy, MacGyver and Rohan', 67);
insert into Supplier (SupplierName, AddressID) values ('O''Conner-Hayes', 841);
insert into Supplier (SupplierName, AddressID) values ('Doyle, Heidenreich and Shields', 465);
insert into Supplier (SupplierName, AddressID) values ('Rutherford-Lindgren', 4);
insert into Supplier (SupplierName, AddressID) values ('Anderson LLC', 285);
insert into Supplier (SupplierName, AddressID) values ('Reinger Inc', 606);
insert into Supplier (SupplierName, AddressID) values ('Streich and Sons', 521);
insert into Supplier (SupplierName, AddressID) values ('Nikolaus LLC', 31);
insert into Supplier (SupplierName, AddressID) values ('Mertz, Adams and Hegmann', 574);
insert into Supplier (SupplierName, AddressID) values ('Berge-Mraz', 871);
insert into Supplier (SupplierName, AddressID) values ('Erdman Inc', 786);
insert into Supplier (SupplierName, AddressID) values ('Lakin and Sons', 134);
insert into Supplier (SupplierName, AddressID) values ('Toy, Kub and Keeling', 695);
insert into Supplier (SupplierName, AddressID) values ('Goldner-Beier', 162);
insert into Supplier (SupplierName, AddressID) values ('Macejkovic Inc', 395);
insert into Supplier (SupplierName, AddressID) values ('Bins, Thompson and Lemke', 204);
insert into Supplier (SupplierName, AddressID) values ('Bartoletti and Sons', 889);
insert into Supplier (SupplierName, AddressID) values ('Ankunding and Sons', 340);
insert into Supplier (SupplierName, AddressID) values ('Wolf, Becker and Zieme', 596);
insert into Supplier (SupplierName, AddressID) values ('Ondricka, O''Hara and Kris', 941);
insert into Supplier (SupplierName, AddressID) values ('Corkery Inc', 494);
insert into Supplier (SupplierName, AddressID) values ('Gleason LLC', 944);
insert into Supplier (SupplierName, AddressID) values ('Christiansen-Jones', 356);
insert into Supplier (SupplierName, AddressID) values ('Cremin-Reynolds', 27);
insert into Supplier (SupplierName, AddressID) values ('Kozey LLC', 546);
insert into Supplier (SupplierName, AddressID) values ('White LLC', 282);
insert into Supplier (SupplierName, AddressID) values ('Heaney, Ullrich and Rau', 563);
insert into Supplier (SupplierName, AddressID) values ('Ryan Group', 443);
insert into Supplier (SupplierName, AddressID) values ('Buckridge Inc', 671);
insert into Supplier (SupplierName, AddressID) values ('Reinger and Sons', 258);
insert into Supplier (SupplierName, AddressID) values ('Ullrich, Kerluke and Jaskolski', 209);
insert into Supplier (SupplierName, AddressID) values ('Lubowitz-Dickinson', 25);
insert into Supplier (SupplierName, AddressID) values ('Doyle, Jast and Mitchell', 6);
insert into Supplier (SupplierName, AddressID) values ('Sawayn-Doyle', 96);
insert into Supplier (SupplierName, AddressID) values ('Osinski, Heidenreich and Bayer', 39);
insert into Supplier (SupplierName, AddressID) values ('Schuster-Green', 292);
insert into Supplier (SupplierName, AddressID) values ('Haley-McClure', 966);
insert into Supplier (SupplierName, AddressID) values ('Hartmann-Bahringer', 3);
insert into Supplier (SupplierName, AddressID) values ('McCullough and Sons', 112);
insert into Supplier (SupplierName, AddressID) values ('Schuster LLC', 916);
insert into Supplier (SupplierName, AddressID) values ('Moen-Schaden', 23);
insert into Supplier (SupplierName, AddressID) values ('Rodriguez-Sanford', 650);
insert into Supplier (SupplierName, AddressID) values ('Crona-Friesen', 26);
insert into Supplier (SupplierName, AddressID) values ('Rutherford-Cruickshank', 905);
insert into Supplier (SupplierName, AddressID) values ('Hamill Inc', 844);
insert into Supplier (SupplierName, AddressID) values ('Funk-Rau', 575);
insert into Supplier (SupplierName, AddressID) values ('Heaney Group', 614);
insert into Supplier (SupplierName, AddressID) values ('Kovacek Group', 791);
insert into Supplier (SupplierName, AddressID) values ('Sauer-Farrell', 181);
insert into Supplier (SupplierName, AddressID) values ('Beier and Sons', 583);
insert into Supplier (SupplierName, AddressID) values ('Zboncak, Wolf and Langworth', 303);
insert into Supplier (SupplierName, AddressID) values ('Gerlach-Becker', 553);
insert into Supplier (SupplierName, AddressID) values ('Schuppe, Heller and Thompson', 509);
insert into Supplier (SupplierName, AddressID) values ('Durgan, Spinka and Pfannerstill', 544);
insert into Supplier (SupplierName, AddressID) values ('Stroman LLC', 695);
insert into Supplier (SupplierName, AddressID) values ('Beier Inc', 242);
insert into Supplier (SupplierName, AddressID) values ('Harvey, Grant and Stiedemann', 933);
insert into Supplier (SupplierName, AddressID) values ('Gutmann-Sipes', 298);
insert into Supplier (SupplierName, AddressID) values ('Romaguera-Blick', 971);
insert into Supplier (SupplierName, AddressID) values ('Witting-Maggio', 555);
insert into Supplier (SupplierName, AddressID) values ('Lueilwitz LLC', 852);
insert into Supplier (SupplierName, AddressID) values ('Brown Inc', 607);
insert into Supplier (SupplierName, AddressID) values ('Donnelly Inc', 132);
insert into Supplier (SupplierName, AddressID) values ('Kessler-Howe', 106);
insert into Supplier (SupplierName, AddressID) values ('Hills Inc', 762);
insert into Supplier (SupplierName, AddressID) values ('Beahan and Sons', 255);
insert into Supplier (SupplierName, AddressID) values ('Witting, Murphy and Leuschke', 393);
insert into Supplier (SupplierName, AddressID) values ('Howell, Bogisich and Jacobs', 21);
insert into Supplier (SupplierName, AddressID) values ('Grady-Ernser', 194);
insert into Supplier (SupplierName, AddressID) values ('Kemmer LLC', 171);
insert into Supplier (SupplierName, AddressID) values ('Gulgowski LLC', 946);
insert into Supplier (SupplierName, AddressID) values ('Homenick-Bogisich', 796);
insert into Supplier (SupplierName, AddressID) values ('Mueller, Gleichner and Kshlerin', 765);
insert into Supplier (SupplierName, AddressID) values ('Volkman-Schuster', 358);
insert into Supplier (SupplierName, AddressID) values ('Welch LLC', 648);
insert into Supplier (SupplierName, AddressID) values ('Hagenes LLC', 24);
insert into Supplier (SupplierName, AddressID) values ('Predovic LLC', 41);
insert into Supplier (SupplierName, AddressID) values ('Nienow Inc', 74);
insert into Supplier (SupplierName, AddressID) values ('Raynor-Stiedemann', 96);
insert into Supplier (SupplierName, AddressID) values ('Hammes and Sons', 876);
insert into Supplier (SupplierName, AddressID) values ('Hoeger, Little and Von', 355);
insert into Supplier (SupplierName, AddressID) values ('Nicolas, Marks and Muller', 130);
insert into Supplier (SupplierName, AddressID) values ('Barton, Hagenes and Lehner', 657);
insert into Supplier (SupplierName, AddressID) values ('Sanford-Littel', 993);
insert into Supplier (SupplierName, AddressID) values ('Pfannerstill Group', 985);
insert into Supplier (SupplierName, AddressID) values ('Fritsch, Berge and Wolff', 629);
insert into Supplier (SupplierName, AddressID) values ('Maggio-Bergnaum', 179);
insert into Supplier (SupplierName, AddressID) values ('Zieme-Bruen', 505);
insert into Supplier (SupplierName, AddressID) values ('Turner Inc', 523);
insert into Supplier (SupplierName, AddressID) values ('Windler-Goldner', 329);
insert into Supplier (SupplierName, AddressID) values ('Huels and Sons', 520);
insert into Supplier (SupplierName, AddressID) values ('Ratke, Legros and Koss', 346);
insert into Supplier (SupplierName, AddressID) values ('Dach Group', 626);
insert into Supplier (SupplierName, AddressID) values ('Daniel and Sons', 645);
insert into Supplier (SupplierName, AddressID) values ('Schiller Group', 198);
insert into Supplier (SupplierName, AddressID) values ('Harvey-Turcotte', 64);
insert into Supplier (SupplierName, AddressID) values ('Deckow-O''Reilly', 640);
insert into Supplier (SupplierName, AddressID) values ('Hagenes LLC', 367);
insert into Supplier (SupplierName, AddressID) values ('Schumm-Rutherford', 925);
insert into Supplier (SupplierName, AddressID) values ('Bailey, Purdy and Legros', 206);
insert into Supplier (SupplierName, AddressID) values ('Borer, Mayer and Marks', 303);
insert into Supplier (SupplierName, AddressID) values ('Harvey-Schumm', 127);
insert into Supplier (SupplierName, AddressID) values ('Borer Inc', 42);
insert into Supplier (SupplierName, AddressID) values ('Schaefer, Veum and Abbott', 420);
insert into Supplier (SupplierName, AddressID) values ('Hermiston-Treutel', 51);
insert into Supplier (SupplierName, AddressID) values ('Hermann Group', 37);
insert into Supplier (SupplierName, AddressID) values ('Predovic-Flatley', 437);
insert into Supplier (SupplierName, AddressID) values ('Green Inc', 395);
insert into Supplier (SupplierName, AddressID) values ('Kub LLC', 511);
insert into Supplier (SupplierName, AddressID) values ('Emard, Raynor and Jenkins', 839);
insert into Supplier (SupplierName, AddressID) values ('Stamm-Schoen', 118);
insert into Supplier (SupplierName, AddressID) values ('Wilderman, Johns and Schuster', 573);
insert into Supplier (SupplierName, AddressID) values ('Roberts-Tillman', 88);
insert into Supplier (SupplierName, AddressID) values ('Klocko, Towne and Senger', 688);
insert into Supplier (SupplierName, AddressID) values ('Champlin-Russel', 302);
insert into Supplier (SupplierName, AddressID) values ('Harris, Corwin and Waters', 836);
insert into Supplier (SupplierName, AddressID) values ('Haag-Bartoletti', 313);
insert into Supplier (SupplierName, AddressID) values ('Fay, Morar and Botsford', 28);
insert into Supplier (SupplierName, AddressID) values ('Rodriguez, Crona and Jenkins', 324);
insert into Supplier (SupplierName, AddressID) values ('Dietrich LLC', 569);
insert into Supplier (SupplierName, AddressID) values ('Baumbach, Waters and Kozey', 115);
insert into Supplier (SupplierName, AddressID) values ('Treutel, Schimmel and Weber', 906);
insert into Supplier (SupplierName, AddressID) values ('Beer-O''Connell', 747);
insert into Supplier (SupplierName, AddressID) values ('Schamberger, Upton and Kohler', 720);
insert into Supplier (SupplierName, AddressID) values ('Skiles, Swift and Windler', 816);
insert into Supplier (SupplierName, AddressID) values ('Crona LLC', 965);
insert into Supplier (SupplierName, AddressID) values ('Hodkiewicz-Connelly', 860);
insert into Supplier (SupplierName, AddressID) values ('Trantow-Paucek', 228);
insert into Supplier (SupplierName, AddressID) values ('Wolf LLC', 989);
insert into Supplier (SupplierName, AddressID) values ('Bednar and Sons', 255);
insert into Supplier (SupplierName, AddressID) values ('Huel-Schneider', 982);
insert into Supplier (SupplierName, AddressID) values ('Roberts, Funk and Senger', 875);
insert into Supplier (SupplierName, AddressID) values ('Hudson-Bogisich', 17);
insert into Supplier (SupplierName, AddressID) values ('Halvorson and Sons', 163);
insert into Supplier (SupplierName, AddressID) values ('Bernier LLC', 607);
insert into Supplier (SupplierName, AddressID) values ('Johnson-Goyette', 596);
insert into Supplier (SupplierName, AddressID) values ('Thiel, Steuber and Turcotte', 423);
insert into Supplier (SupplierName, AddressID) values ('Macejkovic-Nitzsche', 881);
insert into Supplier (SupplierName, AddressID) values ('Miller-Gibson', 310);
insert into Supplier (SupplierName, AddressID) values ('Hills Inc', 578);
insert into Supplier (SupplierName, AddressID) values ('Kerluke and Sons', 447);
insert into Supplier (SupplierName, AddressID) values ('Johnson-Ondricka', 342);
insert into Supplier (SupplierName, AddressID) values ('Roob Group', 864);
insert into Supplier (SupplierName, AddressID) values ('Brakus LLC', 581);
insert into Supplier (SupplierName, AddressID) values ('Cormier Group', 853);
insert into Supplier (SupplierName, AddressID) values ('Donnelly-Robel', 675);
insert into Supplier (SupplierName, AddressID) values ('Haley, Hilll and Homenick', 892);
insert into Supplier (SupplierName, AddressID) values ('Johnson-Schumm', 217);
insert into Supplier (SupplierName, AddressID) values ('Hammes, Langworth and Leffler', 280);
insert into Supplier (SupplierName, AddressID) values ('McCullough and Sons', 65);
insert into Supplier (SupplierName, AddressID) values ('Boyle-Rutherford', 995);
insert into Supplier (SupplierName, AddressID) values ('Larkin LLC', 828);
insert into Supplier (SupplierName, AddressID) values ('Wyman LLC', 503);
insert into Supplier (SupplierName, AddressID) values ('Gaylord and Sons', 526);
insert into Supplier (SupplierName, AddressID) values ('Kunde, Steuber and Herman', 192);
insert into Supplier (SupplierName, AddressID) values ('Nikolaus, Baumbach and Jaskolski', 313);
insert into Supplier (SupplierName, AddressID) values ('Barrows-Flatley', 497);
insert into Supplier (SupplierName, AddressID) values ('Trantow Group', 26);
insert into Supplier (SupplierName, AddressID) values ('Fay and Sons', 119);
insert into Supplier (SupplierName, AddressID) values ('Grady LLC', 339);
insert into Supplier (SupplierName, AddressID) values ('Hayes-Schmitt', 899);
insert into Supplier (SupplierName, AddressID) values ('Hartmann, Schuppe and Abbott', 703);
insert into Supplier (SupplierName, AddressID) values ('Hermiston-Hirthe', 640);
insert into Supplier (SupplierName, AddressID) values ('Abbott-Bednar', 611);
insert into Supplier (SupplierName, AddressID) values ('Ledner, Sporer and Keeling', 235);
insert into Supplier (SupplierName, AddressID) values ('Durgan, Ledner and Graham', 804);
insert into Supplier (SupplierName, AddressID) values ('Rogahn Inc', 934);
insert into Supplier (SupplierName, AddressID) values ('Strosin Group', 794);
insert into Supplier (SupplierName, AddressID) values ('Lemke and Sons', 285);
insert into Supplier (SupplierName, AddressID) values ('Orn Group', 714);
insert into Supplier (SupplierName, AddressID) values ('Hoeger-Schimmel', 652);
insert into Supplier (SupplierName, AddressID) values ('Jast-Mante', 582);
insert into Supplier (SupplierName, AddressID) values ('Jaskolski-Dibbert', 207);
insert into Supplier (SupplierName, AddressID) values ('Steuber, Greenfelder and Mitchell', 627);
insert into Supplier (SupplierName, AddressID) values ('Anderson-Littel', 982);
insert into Supplier (SupplierName, AddressID) values ('Monahan and Sons', 704);
insert into Supplier (SupplierName, AddressID) values ('Lockman, Hessel and Sporer', 485);
insert into Supplier (SupplierName, AddressID) values ('Spencer Group', 519);
insert into Supplier (SupplierName, AddressID) values ('Trantow Inc', 873);
insert into Supplier (SupplierName, AddressID) values ('Schamberger-Boyer', 446);
insert into Supplier (SupplierName, AddressID) values ('Murphy and Sons', 322);
insert into Supplier (SupplierName, AddressID) values ('Rippin, Monahan and Haley', 941);
insert into Supplier (SupplierName, AddressID) values ('Reynolds-Rath', 383);
insert into Supplier (SupplierName, AddressID) values ('Franecki, Collier and Kulas', 329);
insert into Supplier (SupplierName, AddressID) values ('Hegmann, Mitchell and Volkman', 488);
insert into Supplier (SupplierName, AddressID) values ('McLaughlin, Hoppe and Parisian', 647);
insert into Supplier (SupplierName, AddressID) values ('Gaylord and Sons', 485);
insert into Supplier (SupplierName, AddressID) values ('Little Group', 730);
insert into Supplier (SupplierName, AddressID) values ('Crist-Leffler', 861);
insert into Supplier (SupplierName, AddressID) values ('Gerhold-Schamberger', 390);
insert into Supplier (SupplierName, AddressID) values ('Cremin-Stokes', 41);
insert into Supplier (SupplierName, AddressID) values ('Schuster-Bauch', 533);
insert into Supplier (SupplierName, AddressID) values ('Nienow-Smith', 796);
insert into Supplier (SupplierName, AddressID) values ('Wolf-Reichert', 323);
insert into Supplier (SupplierName, AddressID) values ('Rodriguez, Turcotte and Hoppe', 954);
insert into Supplier (SupplierName, AddressID) values ('Jenkins Group', 328);
insert into Supplier (SupplierName, AddressID) values ('Keebler-Barton', 280);
insert into Supplier (SupplierName, AddressID) values ('Quitzon-Christiansen', 269);
insert into Supplier (SupplierName, AddressID) values ('Kuphal, Hodkiewicz and Kunze', 369);
insert into Supplier (SupplierName, AddressID) values ('Reichel, Kassulke and Murray', 520);
insert into Supplier (SupplierName, AddressID) values ('Goodwin, Reilly and Jenkins', 19);
insert into Supplier (SupplierName, AddressID) values ('Schowalter, Conn and Gleichner', 916);
insert into Supplier (SupplierName, AddressID) values ('Hane, McKenzie and Klein', 694);
insert into Supplier (SupplierName, AddressID) values ('Fay, Rice and MacGyver', 568);
insert into Supplier (SupplierName, AddressID) values ('Kovacek-Hintz', 14);
insert into Supplier (SupplierName, AddressID) values ('Schumm Inc', 305);
insert into Supplier (SupplierName, AddressID) values ('Nitzsche-Osinski', 230);
insert into Supplier (SupplierName, AddressID) values ('Spinka-Sporer', 310);
insert into Supplier (SupplierName, AddressID) values ('Williamson, Hartmann and Denesik', 558);
insert into Supplier (SupplierName, AddressID) values ('Batz, Abbott and Cartwright', 155);
insert into Supplier (SupplierName, AddressID) values ('McDermott, Boehm and Davis', 974);
insert into Supplier (SupplierName, AddressID) values ('Grimes, Eichmann and Leannon', 774);
insert into Supplier (SupplierName, AddressID) values ('Trantow-Runolfsson', 920);
insert into Supplier (SupplierName, AddressID) values ('Beatty-Dooley', 946);
insert into Supplier (SupplierName, AddressID) values ('McKenzie, Macejkovic and Luettgen', 493);
insert into Supplier (SupplierName, AddressID) values ('Kreiger-Ebert', 266);
insert into Supplier (SupplierName, AddressID) values ('Harris-Mante', 534);
insert into Supplier (SupplierName, AddressID) values ('Sawayn-McGlynn', 946);
insert into Supplier (SupplierName, AddressID) values ('Grady Group', 695);
insert into Supplier (SupplierName, AddressID) values ('Murray LLC', 547);
insert into Supplier (SupplierName, AddressID) values ('Kemmer Group', 407);
insert into Supplier (SupplierName, AddressID) values ('Nitzsche-Bailey', 236);
insert into Supplier (SupplierName, AddressID) values ('Corkery-Abernathy', 95);
insert into Supplier (SupplierName, AddressID) values ('Bednar, Jacobs and Donnelly', 477);
insert into Supplier (SupplierName, AddressID) values ('Kassulke LLC', 290);
insert into Supplier (SupplierName, AddressID) values ('Erdman-Grimes', 288);
insert into Supplier (SupplierName, AddressID) values ('Crist Inc', 197);
insert into Supplier (SupplierName, AddressID) values ('Quigley and Sons', 417);
insert into Supplier (SupplierName, AddressID) values ('Franecki-Gerlach', 566);
insert into Supplier (SupplierName, AddressID) values ('McDermott, Von and Leffler', 11);
insert into Supplier (SupplierName, AddressID) values ('Boyle LLC', 884);
insert into Supplier (SupplierName, AddressID) values ('Farrell, Miller and Stracke', 155);
insert into Supplier (SupplierName, AddressID) values ('Renner-Rau', 434);
insert into Supplier (SupplierName, AddressID) values ('Kautzer and Sons', 956);
insert into Supplier (SupplierName, AddressID) values ('Hickle Group', 134);
insert into Supplier (SupplierName, AddressID) values ('White-Sawayn', 739);
insert into Supplier (SupplierName, AddressID) values ('Crona and Sons', 632);
insert into Supplier (SupplierName, AddressID) values ('Schneider, Weissnat and Bayer', 241);
insert into Supplier (SupplierName, AddressID) values ('Jones, Frami and White', 789);
insert into Supplier (SupplierName, AddressID) values ('Kassulke, Bosco and Hegmann', 993);
insert into Supplier (SupplierName, AddressID) values ('Heathcote, Marvin and Rath', 307);
insert into Supplier (SupplierName, AddressID) values ('Harris-Hermann', 85);
insert into Supplier (SupplierName, AddressID) values ('Roob, Hettinger and Fay', 425);
insert into Supplier (SupplierName, AddressID) values ('Schimmel LLC', 635);
insert into Supplier (SupplierName, AddressID) values ('Ruecker, Kuhic and Lockman', 940);
insert into Supplier (SupplierName, AddressID) values ('Kautzer and Sons', 63);
insert into Supplier (SupplierName, AddressID) values ('Ward-Larson', 161);
insert into Supplier (SupplierName, AddressID) values ('Lowe, O''Kon and Kris', 177);
insert into Supplier (SupplierName, AddressID) values ('Schuster, Muller and Zboncak', 729);
insert into Supplier (SupplierName, AddressID) values ('Ullrich, Walter and Rutherford', 716);
insert into Supplier (SupplierName, AddressID) values ('Reichert and Sons', 288);
insert into Supplier (SupplierName, AddressID) values ('Botsford, Abshire and Dickinson', 820);
insert into Supplier (SupplierName, AddressID) values ('Ward-Dach', 101);
insert into Supplier (SupplierName, AddressID) values ('Miller Inc', 674);
insert into Supplier (SupplierName, AddressID) values ('Friesen-Ward', 856);
insert into Supplier (SupplierName, AddressID) values ('Anderson-Block', 21);
insert into Supplier (SupplierName, AddressID) values ('O''Hara-Daugherty', 345);
insert into Supplier (SupplierName, AddressID) values ('Thiel and Sons', 305);
insert into Supplier (SupplierName, AddressID) values ('Okuneva-Towne', 490);
insert into Supplier (SupplierName, AddressID) values ('Bartoletti, Kovacek and Zemlak', 385);
insert into Supplier (SupplierName, AddressID) values ('Wiza-O''Reilly', 60);
insert into Supplier (SupplierName, AddressID) values ('Hackett, Fritsch and Feeney', 758);
insert into Supplier (SupplierName, AddressID) values ('Schneider Group', 258);
insert into Supplier (SupplierName, AddressID) values ('Donnelly-Sauer', 376);
insert into Supplier (SupplierName, AddressID) values ('Gibson-Deckow', 380);
insert into Supplier (SupplierName, AddressID) values ('Stehr Inc', 276);
insert into Supplier (SupplierName, AddressID) values ('Johnson-Harris', 733);
insert into Supplier (SupplierName, AddressID) values ('Mosciski and Sons', 837);
insert into Supplier (SupplierName, AddressID) values ('Flatley Inc', 101);
insert into Supplier (SupplierName, AddressID) values ('Lemke and Sons', 997);
insert into Supplier (SupplierName, AddressID) values ('Fay Inc', 964);
insert into Supplier (SupplierName, AddressID) values ('Mueller LLC', 981);
insert into Supplier (SupplierName, AddressID) values ('Abbott LLC', 832);
insert into Supplier (SupplierName, AddressID) values ('Goodwin Inc', 588);
insert into Supplier (SupplierName, AddressID) values ('Walter, Beer and Effertz', 824);
insert into Supplier (SupplierName, AddressID) values ('Lang Inc', 853);
insert into Supplier (SupplierName, AddressID) values ('Murray, Zemlak and Ryan', 399);
insert into Supplier (SupplierName, AddressID) values ('Walsh-Kirlin', 922);
insert into Supplier (SupplierName, AddressID) values ('Wisoky LLC', 274);
insert into Supplier (SupplierName, AddressID) values ('Dibbert-Grant', 361);
insert into Supplier (SupplierName, AddressID) values ('Bechtelar, Runte and Schulist', 978);
insert into Supplier (SupplierName, AddressID) values ('Orn LLC', 632);
insert into Supplier (SupplierName, AddressID) values ('Kuhic-Skiles', 183);
insert into Supplier (SupplierName, AddressID) values ('Roob LLC', 79);
insert into Supplier (SupplierName, AddressID) values ('Lemke Inc', 257);
insert into Supplier (SupplierName, AddressID) values ('Halvorson Group', 764);
insert into Supplier (SupplierName, AddressID) values ('Hahn and Sons', 953);
insert into Supplier (SupplierName, AddressID) values ('Senger, Kling and Aufderhar', 711);
insert into Supplier (SupplierName, AddressID) values ('Gutmann Inc', 984);
insert into Supplier (SupplierName, AddressID) values ('Schaden-Kassulke', 766);
insert into Supplier (SupplierName, AddressID) values ('Cruickshank-Upton', 291);
insert into Supplier (SupplierName, AddressID) values ('Wilderman, Ward and Leannon', 581);
insert into Supplier (SupplierName, AddressID) values ('Roob-Auer', 152);
insert into Supplier (SupplierName, AddressID) values ('Zemlak-Lubowitz', 836);
insert into Supplier (SupplierName, AddressID) values ('Bradtke, Schuppe and Howell', 641);
insert into Supplier (SupplierName, AddressID) values ('Hettinger-Walker', 544);
insert into Supplier (SupplierName, AddressID) values ('Cruickshank, Kshlerin and Purdy', 865);
insert into Supplier (SupplierName, AddressID) values ('Keebler LLC', 90);
insert into Supplier (SupplierName, AddressID) values ('Durgan-Huels', 253);
insert into Supplier (SupplierName, AddressID) values ('Lowe-Romaguera', 199);
insert into Supplier (SupplierName, AddressID) values ('Rippin-Muller', 327);
insert into Supplier (SupplierName, AddressID) values ('Gibson, McDermott and Durgan', 70);
insert into Supplier (SupplierName, AddressID) values ('Conn, Emard and Gislason', 512);
insert into Supplier (SupplierName, AddressID) values ('Kshlerin, Thiel and Zulauf', 456);
insert into Supplier (SupplierName, AddressID) values ('Daugherty-Lindgren', 798);
insert into Supplier (SupplierName, AddressID) values ('Wiegand-Parker', 335);
insert into Supplier (SupplierName, AddressID) values ('Lowe-Russel', 247);
insert into Supplier (SupplierName, AddressID) values ('Mueller, Ruecker and Durgan', 423);
insert into Supplier (SupplierName, AddressID) values ('Rohan Group', 776);
insert into Supplier (SupplierName, AddressID) values ('Haley Inc', 119);
insert into Supplier (SupplierName, AddressID) values ('Robel-Powlowski', 522);
insert into Supplier (SupplierName, AddressID) values ('Mraz-Bergnaum', 391);
insert into Supplier (SupplierName, AddressID) values ('Maggio, Williamson and Pagac', 836);
insert into Supplier (SupplierName, AddressID) values ('Kuvalis and Sons', 600);
insert into Supplier (SupplierName, AddressID) values ('Bayer-Rosenbaum', 300);
insert into Supplier (SupplierName, AddressID) values ('Kub, Leuschke and Goldner', 368);
insert into Supplier (SupplierName, AddressID) values ('Hane, Zulauf and Hauck', 35);
insert into Supplier (SupplierName, AddressID) values ('Abshire, Beier and Bruen', 887);
insert into Supplier (SupplierName, AddressID) values ('Kreiger and Sons', 41);
insert into Supplier (SupplierName, AddressID) values ('Cremin-Schiller', 533);
insert into Supplier (SupplierName, AddressID) values ('O''Kon-Kuhlman', 119);
insert into Supplier (SupplierName, AddressID) values ('Schoen, Walker and Legros', 527);
insert into Supplier (SupplierName, AddressID) values ('Rice-Howell', 453);
insert into Supplier (SupplierName, AddressID) values ('Grady and Sons', 429);
insert into Supplier (SupplierName, AddressID) values ('Lemke Inc', 603);
insert into Supplier (SupplierName, AddressID) values ('Welch Inc', 387);
insert into Supplier (SupplierName, AddressID) values ('Luettgen LLC', 570);
insert into Supplier (SupplierName, AddressID) values ('Morar LLC', 58);
insert into Supplier (SupplierName, AddressID) values ('Daugherty, McClure and Schmeler', 390);
insert into Supplier (SupplierName, AddressID) values ('Ankunding Group', 518);
insert into Supplier (SupplierName, AddressID) values ('Witting-Baumbach', 199);
insert into Supplier (SupplierName, AddressID) values ('Sanford and Sons', 340);
insert into Supplier (SupplierName, AddressID) values ('Ratke, Blick and Gorczany', 781);
insert into Supplier (SupplierName, AddressID) values ('Kuhic, Hoppe and Swaniawski', 578);
insert into Supplier (SupplierName, AddressID) values ('Hoeger LLC', 739);
insert into Supplier (SupplierName, AddressID) values ('Deckow-Veum', 710);
insert into Supplier (SupplierName, AddressID) values ('Orn, Reichel and Bahringer', 519);
insert into Supplier (SupplierName, AddressID) values ('Cormier-Gottlieb', 582);
insert into Supplier (SupplierName, AddressID) values ('Abbott Inc', 523);
insert into Supplier (SupplierName, AddressID) values ('Deckow-Funk', 479);
insert into Supplier (SupplierName, AddressID) values ('Jones-Ondricka', 10);
insert into Supplier (SupplierName, AddressID) values ('Lakin Group', 670);
insert into Supplier (SupplierName, AddressID) values ('O''Keefe and Sons', 328);
insert into Supplier (SupplierName, AddressID) values ('Gerhold, Olson and Botsford', 811);
insert into Supplier (SupplierName, AddressID) values ('Bruen, Vandervort and Beer', 278);
insert into Supplier (SupplierName, AddressID) values ('Rau, Cartwright and Ruecker', 289);
insert into Supplier (SupplierName, AddressID) values ('Waters and Sons', 665);
insert into Supplier (SupplierName, AddressID) values ('Hayes, Schneider and Medhurst', 751);
insert into Supplier (SupplierName, AddressID) values ('Hamill-Prosacco', 438);
insert into Supplier (SupplierName, AddressID) values ('Simonis Inc', 351);
insert into Supplier (SupplierName, AddressID) values ('Schmidt-Roberts', 492);
insert into Supplier (SupplierName, AddressID) values ('Walsh Group', 184);
insert into Supplier (SupplierName, AddressID) values ('Torphy-Prohaska', 231);
insert into Supplier (SupplierName, AddressID) values ('Ondricka Inc', 653);
insert into Supplier (SupplierName, AddressID) values ('Raynor-Abshire', 448);
insert into Supplier (SupplierName, AddressID) values ('Hintz and Sons', 633);
insert into Supplier (SupplierName, AddressID) values ('O''Kon, Hahn and Stark', 971);
insert into Supplier (SupplierName, AddressID) values ('Dare, Volkman and Berge', 697);
insert into Supplier (SupplierName, AddressID) values ('Blanda Inc', 139);
insert into Supplier (SupplierName, AddressID) values ('Wunsch, Huels and Rempel', 646);
insert into Supplier (SupplierName, AddressID) values ('Morar-Schmeler', 115);
insert into Supplier (SupplierName, AddressID) values ('Pollich, Rowe and Rice', 428);
insert into Supplier (SupplierName, AddressID) values ('Murazik Group', 985);
insert into Supplier (SupplierName, AddressID) values ('Kuhn and Sons', 778);
insert into Supplier (SupplierName, AddressID) values ('Howell LLC', 150);
insert into Supplier (SupplierName, AddressID) values ('Cartwright and Sons', 682);
insert into Supplier (SupplierName, AddressID) values ('Mann, Abshire and Bartell', 80);
insert into Supplier (SupplierName, AddressID) values ('Torphy Group', 808);
insert into Supplier (SupplierName, AddressID) values ('Runolfsson, Fadel and Bins', 677);
insert into Supplier (SupplierName, AddressID) values ('Wilkinson and Sons', 231);
insert into Supplier (SupplierName, AddressID) values ('Mosciski, Yost and Stracke', 354);
insert into Supplier (SupplierName, AddressID) values ('Littel Inc', 661);
insert into Supplier (SupplierName, AddressID) values ('Eichmann LLC', 351);
insert into Supplier (SupplierName, AddressID) values ('Bartoletti, Kutch and Schulist', 634);
insert into Supplier (SupplierName, AddressID) values ('Bechtelar and Sons', 796);
insert into Supplier (SupplierName, AddressID) values ('Kautzer-Kshlerin', 835);
insert into Supplier (SupplierName, AddressID) values ('Durgan-Roberts', 12);
insert into Supplier (SupplierName, AddressID) values ('Klein, Farrell and Nitzsche', 737);
insert into Supplier (SupplierName, AddressID) values ('Hessel, Feil and Satterfield', 748);
insert into Supplier (SupplierName, AddressID) values ('Balistreri, Gleichner and Smith', 250);
insert into Supplier (SupplierName, AddressID) values ('Sauer, Crist and Larkin', 960);
insert into Supplier (SupplierName, AddressID) values ('Lebsack, Abshire and Emmerich', 758);
insert into Supplier (SupplierName, AddressID) values ('King-Schmeler', 572);
insert into Supplier (SupplierName, AddressID) values ('Kshlerin, Moore and White', 53);
insert into Supplier (SupplierName, AddressID) values ('McGlynn, Prohaska and Prohaska', 750);
insert into Supplier (SupplierName, AddressID) values ('Cummerata-Waters', 455);
insert into Supplier (SupplierName, AddressID) values ('Mills-Jenkins', 500);
insert into Supplier (SupplierName, AddressID) values ('Roberts-McKenzie', 652);
insert into Supplier (SupplierName, AddressID) values ('Corwin-Strosin', 225);
insert into Supplier (SupplierName, AddressID) values ('Hegmann, Crooks and Brakus', 490);
insert into Supplier (SupplierName, AddressID) values ('Bechtelar Group', 862);
insert into Supplier (SupplierName, AddressID) values ('Kessler Group', 395);
insert into Supplier (SupplierName, AddressID) values ('Rempel Group', 543);
insert into Supplier (SupplierName, AddressID) values ('King, Wisoky and VonRueden', 16);
insert into Supplier (SupplierName, AddressID) values ('Renner, Goodwin and Jacobson', 994);
insert into Supplier (SupplierName, AddressID) values ('Schmitt-Keeling', 464);
insert into Supplier (SupplierName, AddressID) values ('Wolf-Dach', 95);
insert into Supplier (SupplierName, AddressID) values ('Dickinson, Lubowitz and Dach', 643);
insert into Supplier (SupplierName, AddressID) values ('Schoen LLC', 258);
insert into Supplier (SupplierName, AddressID) values ('Balistreri-Hagenes', 337);
insert into Supplier (SupplierName, AddressID) values ('Romaguera Group', 50);
insert into Supplier (SupplierName, AddressID) values ('Daniel-Upton', 87);
insert into Supplier (SupplierName, AddressID) values ('Willms-Denesik', 982);
insert into Supplier (SupplierName, AddressID) values ('Marks LLC', 27);
insert into Supplier (SupplierName, AddressID) values ('Rice LLC', 683);
insert into Supplier (SupplierName, AddressID) values ('Connelly-Gleichner', 604);
insert into Supplier (SupplierName, AddressID) values ('Marquardt and Sons', 212);
insert into Supplier (SupplierName, AddressID) values ('Waters LLC', 271);
insert into Supplier (SupplierName, AddressID) values ('Leffler-Bailey', 791);
insert into Supplier (SupplierName, AddressID) values ('Johnston Inc', 993);
insert into Supplier (SupplierName, AddressID) values ('Hoppe Inc', 304);
insert into Supplier (SupplierName, AddressID) values ('Kling, Medhurst and Skiles', 244);
insert into Supplier (SupplierName, AddressID) values ('Steuber, Aufderhar and Herman', 476);
insert into Supplier (SupplierName, AddressID) values ('Adams, Shields and Kreiger', 942);
insert into Supplier (SupplierName, AddressID) values ('Smitham, Rath and Beatty', 987);
insert into Supplier (SupplierName, AddressID) values ('Hilpert-Hoeger', 501);
insert into Supplier (SupplierName, AddressID) values ('Rodriguez Inc', 102);
insert into Supplier (SupplierName, AddressID) values ('Weissnat Group', 15);
insert into Supplier (SupplierName, AddressID) values ('Rowe-Robel', 634);
insert into Supplier (SupplierName, AddressID) values ('Sipes, Reynolds and Boehm', 577);
insert into Supplier (SupplierName, AddressID) values ('Hauck, Zulauf and Ferry', 333);
insert into Supplier (SupplierName, AddressID) values ('Upton-Adams', 97);
insert into Supplier (SupplierName, AddressID) values ('Kling LLC', 389);
insert into Supplier (SupplierName, AddressID) values ('Wilkinson, Shanahan and Weber', 77);
insert into Supplier (SupplierName, AddressID) values ('Champlin-Becker', 775);
insert into Supplier (SupplierName, AddressID) values ('Purdy-Robel', 59);
insert into Supplier (SupplierName, AddressID) values ('Frami, Koelpin and Pouros', 852);
insert into Supplier (SupplierName, AddressID) values ('Carter LLC', 476);
insert into Supplier (SupplierName, AddressID) values ('Cole-Kuphal', 843);
insert into Supplier (SupplierName, AddressID) values ('Eichmann Inc', 718);
insert into Supplier (SupplierName, AddressID) values ('Schmidt Inc', 368);
insert into Supplier (SupplierName, AddressID) values ('Watsica-Gleason', 363);
insert into Supplier (SupplierName, AddressID) values ('Hirthe Group', 458);
insert into Supplier (SupplierName, AddressID) values ('Leannon-Davis', 737);
insert into Supplier (SupplierName, AddressID) values ('Yost Inc', 716);
insert into Supplier (SupplierName, AddressID) values ('Stroman, Williamson and Raynor', 96);
insert into Supplier (SupplierName, AddressID) values ('Simonis-Yost', 660);
insert into Supplier (SupplierName, AddressID) values ('Cummings, Farrell and Bernhard', 121);
insert into Supplier (SupplierName, AddressID) values ('Marks-Tillman', 331);
insert into Supplier (SupplierName, AddressID) values ('Turner LLC', 413);
insert into Supplier (SupplierName, AddressID) values ('Hickle-Bernier', 330);
insert into Supplier (SupplierName, AddressID) values ('Reichel-Reynolds', 789);
insert into Supplier (SupplierName, AddressID) values ('Homenick-Howell', 58);
insert into Supplier (SupplierName, AddressID) values ('Lockman, Terry and Larkin', 468);
insert into Supplier (SupplierName, AddressID) values ('Mayer and Sons', 226);
insert into Supplier (SupplierName, AddressID) values ('Huel-Stroman', 482);
insert into Supplier (SupplierName, AddressID) values ('Abshire, Predovic and Lehner', 999);
insert into Supplier (SupplierName, AddressID) values ('Stokes and Sons', 735);
insert into Supplier (SupplierName, AddressID) values ('Kessler, Marks and Balistreri', 94);
insert into Supplier (SupplierName, AddressID) values ('Runolfsson LLC', 308);
insert into Supplier (SupplierName, AddressID) values ('Stamm Group', 184);
insert into Supplier (SupplierName, AddressID) values ('Yundt-Gutmann', 931);
insert into Supplier (SupplierName, AddressID) values ('Hilll Inc', 706);
insert into Supplier (SupplierName, AddressID) values ('Nicolas-Johnston', 875);
insert into Supplier (SupplierName, AddressID) values ('Schneider, Ferry and Eichmann', 198);
insert into Supplier (SupplierName, AddressID) values ('Hamill, Stark and Gaylord', 898);
insert into Supplier (SupplierName, AddressID) values ('MacGyver, Hegmann and Barrows', 25);
insert into Supplier (SupplierName, AddressID) values ('Bergstrom-Hilll', 828);
insert into Supplier (SupplierName, AddressID) values ('Wolf, Connelly and Mertz', 469);
insert into Supplier (SupplierName, AddressID) values ('Reichel Inc', 449);
insert into Supplier (SupplierName, AddressID) values ('Kertzmann-Wilderman', 498);
insert into Supplier (SupplierName, AddressID) values ('Glover, Baumbach and Green', 871);
insert into Supplier (SupplierName, AddressID) values ('Luettgen LLC', 336);
insert into Supplier (SupplierName, AddressID) values ('Schoen Inc', 937);
insert into Supplier (SupplierName, AddressID) values ('Herman-Kertzmann', 931);
insert into Supplier (SupplierName, AddressID) values ('Kirlin-Haley', 115);
insert into Supplier (SupplierName, AddressID) values ('Goyette and Sons', 850);
insert into Supplier (SupplierName, AddressID) values ('Beatty, Feest and Wiegand', 68);
insert into Supplier (SupplierName, AddressID) values ('Casper Group', 572);
insert into Supplier (SupplierName, AddressID) values ('Breitenberg, Padberg and Krajcik', 181);
insert into Supplier (SupplierName, AddressID) values ('Watsica, Glover and Wisozk', 959);
insert into Supplier (SupplierName, AddressID) values ('Flatley Group', 365);
insert into Supplier (SupplierName, AddressID) values ('Sipes, McGlynn and Price', 132);
insert into Supplier (SupplierName, AddressID) values ('Prohaska-Herzog', 636);
insert into Supplier (SupplierName, AddressID) values ('Hand and Sons', 572);
insert into Supplier (SupplierName, AddressID) values ('Upton-Lueilwitz', 302);
insert into Supplier (SupplierName, AddressID) values ('Jast LLC', 322);
insert into Supplier (SupplierName, AddressID) values ('Tillman LLC', 127);
insert into Supplier (SupplierName, AddressID) values ('Flatley, Padberg and Daniel', 863);
insert into Supplier (SupplierName, AddressID) values ('Stokes Group', 733);
insert into Supplier (SupplierName, AddressID) values ('King-Runte', 197);
insert into Supplier (SupplierName, AddressID) values ('Zieme, Zemlak and Wehner', 27);
insert into Supplier (SupplierName, AddressID) values ('Paucek and Sons', 643);
insert into Supplier (SupplierName, AddressID) values ('Rath-Paucek', 477);
insert into Supplier (SupplierName, AddressID) values ('Dach-Mante', 461);
*/